from datetime import datetime, timedelta
from app.db import get_db

# for when itinerary input fails validation
class ValidationError(Exception):
    pass

_UNSET = object()

# add itinerary to database
# itinerary_id autogenerated primary key
# attributes: trip_id (int), day_number(int), title(str), description(str), activities(str)
def create_itinerary(trip_id, day_number, title=None, description=None, activities=None):
    if not isinstance(day_number, int) or isinstance(day_number, bool) or day_number < 1:
        raise ValidationError("day_number must be a positive integer.")
    
    db = get_db()
    
    db.execute(
        "INSERT INTO itinerary (trip_id, day_number, title, description, activities) VALUES (?, ?, ?, ?, ?)",
        (trip_id, day_number, title, description, activities)
    )
    
    db.commit()

# retrieve itinerary using itinerary id
def get_itinerary_by_id(itinerary_id):
    db = get_db()
    
    return db.execute(
        "SELECT * FROM itinerary WHERE id = ?",
        (itinerary_id,)
    ).fetchone()

# retrieve iternary by trip (trip_id) and day
def get_itinerary_by_trip_and_day(trip_id, day_number):
    db = get_db()
    
    return db.execute(
        "SELECT * FROM itinerary WHERE trip_id = ? AND day_number = ?",
        (trip_id, day_number)
    ).fetchone()

# retrieve itinerary using just trip_id
def get_itinerary_by_trip(trip_id):
    db = get_db()
    
    return db.execute(
        "SELECT * FROM itinerary WHERE trip_id = ? ORDER BY day_number",
        (trip_id,)
    ).fetchall()

# update an itinerary with new dates, title, description, or activities
def update_itinerary(itinerary_id, title=_UNSET, description=_UNSET, activities=_UNSET):
    existing = get_itinerary_by_id(itinerary_id)

    if existing is None:
        raise ValidationError(f"No itinerary entry with id {itinerary_id}.")

    final_title = existing["title"] if title is _UNSET else title
    final_description = existing["description"] if description is _UNSET else description
    final_activities = existing["activities"] if activities is _UNSET else activities
    
    db = get_db()
    
    db.execute(
        "UPDATE itinerary SET title = ?, description = ?, activities = ?, updated_at = ? WHERE id = ?",
        (final_title, final_description, final_activities, datetime.utcnow(), itinerary_id)
    )
    
    db.commit()

# delete an itinerary using itinerary_id# delete an itinerary using itinerary_id 
def delete_itinerary(itinerary_id):
    db = get_db()
    
    db.execute("DELETE FROM itinerary WHERE id = ?", (itinerary_id,))
    db.commit()

# gets date of day using day_number input
# creates offset to track duration of trip
def get_day_date(trip_start_date, day_number):
    day_offset = day_number - 1
    return (trip_start_date + timedelta(days=day_offset)).isoformat()

# marks an itinerary as complete using itinerary_id
def mark_itinerary_complete(itinerary_id):
    db = get_db()
    
    db.execute(
        "UPDATE itinerary SET completed = 1, updated_at = ? WHERE id = ?",
        (datetime.utcnow(), itinerary_id)
    )
    
    db.commit()

# marks an itinerary as incomplete using itinerary_id
def mark_itinerary_incomplete(itinerary_id):
    db = get_db()
    
    db.execute(
        "UPDATE itinerary SET completed = 0, updated_at = ? WHERE id = ?",
        (datetime.utcnow(), itinerary_id)
    )
    
    db.commit()

# get status of trips as total count complete and incompletes + percent of completed trips
def get_trip_completion_status(trip_id):
    db = get_db()
    
    total = db.execute(
        "SELECT COUNT(*) as count FROM itinerary WHERE trip_id = ?",
        (trip_id,)
    ).fetchone()
    
    completed = db.execute(
        "SELECT COUNT(*) as count FROM itinerary WHERE trip_id = ? AND completed = 1",
        (trip_id,)
    ).fetchone()
    
    return {
        'total': total['count'],
        'completed': completed['count'],
        'percentage': (completed['count'] / total['count'] * 100) if total['count'] > 0 else 0
    }
