from datetime import datetime, timedelta
from app.db import get_db
from app.models.trip import get_event_by_id

class ValidationError(Exception):
    pass

# notification types this app currently knows how to send
VALID_NOTIFICATION_TYPES = {'email', 'sms', 'push'}

# add reminder to database
# reminder_id autogenerated primary key
# attributes: event_id(int), user_id(int), minutes_before (int), notification_type (email)
def create_reminder(event_id, user_id, minutes_before, notification_type='email'):
    if not isinstance(minutes_before, int) or isinstance(minutes_before, bool) or minutes_before < 0:
        raise ValidationError("minutes_before must be a non-negative integer.")

    if notification_type not in VALID_NOTIFICATION_TYPES:
        raise ValidationError(f"notification_type must be one of: {sorted(VALID_NOTIFICATION_TYPES)}")

    event = get_event_by_id(event_id)
    if event is None:
        raise ValidationError(f"No event with id {event_id}.")

    event_start = datetime.fromisoformat(event['start_time'])
    reminder_time = event_start - timedelta(minutes=minutes_before)

    db = get_db()

    db.execute(
        "INSERT INTO reminder (event_id, user_id, reminder_time, notification_type) VALUES (?, ?, ?, ?)",
        (event_id, user_id, reminder_time, notification_type)
    )

    db.commit()

# retrieve reminder using event_id
def get_reminders_by_event(event_id):
    db = get_db()

    return db.execute(
        "SELECT * FROM reminder WHERE event_id = ?",
        (event_id,)
    ).fetchall()

# retrieve pending reminders (active but not yet sent)
def get_pending_reminders():
    db = get_db()

    return db.execute(
        "SELECT * FROM reminder WHERE sent = 0 AND reminder_time <= ?",
        (datetime.utcnow(),)
    ).fetchall()

# update reminder as being sent
def mark_reminder_sent(reminder_id):
    db = get_db()

    db.execute("UPDATE reminder SET sent = 1 WHERE id = ?", (reminder_id,))
    db.commit()

# delete reminder using reminder_id
def delete_reminder(reminder_id):
    db = get_db()

    db.execute("DELETE FROM reminder WHERE id = ?", (reminder_id,))
    db.commit()

# retrieve a single reminder by its own id
def get_reminder_by_id(reminder_id):
    db = get_db()

    return db.execute(
        "SELECT * FROM reminder WHERE id = ?",
        (reminder_id,)
    ).fetchone()
