from werkzeug.security import generate_password_hash, check_password_hash
from flask import current_app
from app.db import get_db
from app.utils.validators import is_valid_email, is_valid_password
from datetime import datetime, timedelta
import secrets

'''
Database Attributes:
userid: Identifier (int) SQLite generated primary key
email: type (string)
password, new_password: type (int) Constraints [Lower + Uppercase, Min 8 letters, Special Char, Number]
expires_at: type (date/time)
token: generated string
'''

# Custom exception for validation errors
# return 400 if password fails validation
class ValidationError(Exception):
    pass

# add user to database
# user_id autogenerated primary key
# attributes: email, password (strings)
def create_user(email, password):
    if not email or not is_valid_email(email):
        raise ValidationError("Invalid email format.")

    valid, msg = is_valid_password(password)

    if not valid:
        raise ValidationError(msg)

    db = get_db()

    hashed_password = generate_password_hash(password, method="pbkdf2:sha256")

    cursor = db.execute(
        "INSERT INTO users (email, password_hash) VALUES (?, ?)",
        (email, hashed_password),
    )

    db.commit()

    return cursor.lastrowid

# retrieve user by email address
def get_user_by_email(email):
    db = get_db()

    return db.execute(
        "SELECT * FROM users WHERE email = ?", (email,)
    ).fetchone()

# checks if user password matches database stored one
def verify_password(user, password):
    return check_password_hash(user["password_hash"], password)

# creates reset token to send to email
# UPDATE TO SEND TO USER EMAIL
def create_password_reset_token(user_id):
    db = get_db()

    token = secrets.token_urlsafe(32)
    expires_at = datetime.utcnow() + timedelta(hours=24)

    db.execute(
        "INSERT INTO password_reset_token (user_id, token, expires_at) VALUES (?, ?, ?)",
        (user_id, token, expires_at)
    )

    db.commit()

    return token

# gets token from reset password
def get_password_reset_token(token):
    db = get_db()

    return db.execute(
        "SELECT * FROM password_reset_token WHERE token = ? AND used = 0 AND expires_at > ?",
        (token, datetime.utcnow())
    ).fetchone()

# updates password given new_password
def update_password(user_id, new_password):
    db = get_db()

    hashed_password = generate_password_hash(new_password, method="pbkdf2:sha256")

    db.execute(
        "UPDATE users SET password_hash = ? WHERE id = ?",
        (hashed_password, user_id)
    )

    db.commit()

# Sets reset token as used (reset password process completed)
def mark_reset_token_used(token):
    db = get_db()

    db.execute(
        "UPDATE password_reset_token SET used = 1 WHERE token = ?",
        (token,)
    )

    db.commit()